version: 18
jobs:
- name: Compile
  jobExecutor: local-bare-metal-job-executor
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: compile
    runInContainer: false
    interpreter: !ShellInterpreter
      shell: bash
      commands:
      - ./build_all.sh
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Prepare artifacts
    runInContainer: false
    interpreter: !ShellInterpreter
      shell: bash
      commands:
      - zip artifacts.zip bin/* tests/*
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: Publish build results
    artifacts: artifacts.zip
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
- name: Test
  jobExecutor: local-bare-metal-job-executor
  steps:
  - !CommandStep
    name: Extract artifacts
    runInContainer: false
    interpreter: !ShellInterpreter
      shell: bash
      commands:
      - unzip artifacts.zip
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Run tests
    runInContainer: false
    interpreter: !ShellInterpreter
      shell: bash
      commands:
      - bin/zodiac_tests
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Run compiler
    runInContainer: false
    interpreter: !ShellInterpreter
      shell: bash
      commands:
      - tree
      - bin/zodiac tests/simple.zc -v
      - ./a.out || EXIT_CODE=$?
      - '[[ $EXIT_CODE -eq 85 ]] && exit 0 || echo Invalid exit code $EXIT_CODE; exit
        1'
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !DependencyFinishedTrigger
    projects: zodiac
  jobDependencies:
  - jobName: Compile
    requireSuccessful: true
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
- name: Github sync
  steps:
  - !PushRepository
    name: sync
    remoteUrl: https://github.com/JorriFransen/zodiac.git
    userName: jorri
    passwordSecret: ghsynctoken
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !DependencyFinishedTrigger
    projects: zodiac
  jobDependencies:
  - jobName: Test
    requireSuccessful: true
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
