version: 24
jobs:
- name: CI
  jobExecutor: local-bare-metal-job-executor
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    cloneDepth: 1
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Compile
    runInContainer: false
    image: alpine
    interpreter: !ShellInterpreter
      shell: bash
      commands:
      - make -f Makefile.linux.mak zodiac_tests zodiac_driver -j $(nproc)
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Run tests
    runInContainer: false
    image: alpine
    interpreter: !ShellInterpreter
      shell: bash
      commands:
      - time bin/zodiac_tests
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Run compiler
    runInContainer: false
    image: alpine
    interpreter: !ShellInterpreter
      shell: bash
      commands:
      - bin/zodiac tests/main.zc -v
      - ./main || EXIT_CODE=$?
      - '[[ $EXIT_CODE -eq 0 ]] && exit 0 || echo Invalid exit code $EXIT_CODE; exit
        1'
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Prepare artifacts
    runInContainer: false
    interpreter: !ShellInterpreter
      shell: bash
      commands:
      - patchelf --remove-needed libz3.so.4 bin/libzodiac.so
      - zip artifacts.zip bin/* tests/*
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: Publish artifacts
    artifacts: artifacts.zip
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !PullRequestUpdateTrigger
    projects: zodiac
  - !BranchUpdateTrigger
    branches: main dev
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
  postBuildActions:
  - !RunJobAction
    condition: successful
    jobName: Github sync
- name: Github sync
  jobExecutor: local-bare-metal-job-executor
  steps:
  - !PushRepository
    name: Github sync
    remoteUrl: https://github.com/JorriFransen/zodiac.git
    userName: jorri
    passwordSecret: ghsynctoken
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
