version: 18
jobs:
- name: Github sync
  steps:
  - !PushRepository
    name: sync
    remoteUrl: https://github.com/JorriFransen/zodiac.git
    userName: jorri@jorrifransen.nl
    passwordSecret: ghsynctoken
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
