version: 18
jobs:
- name: Compile
  jobExecutor: local-bare-metal-job-executor
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: compile
    runInContainer: false
    interpreter: !ShellInterpreter
      shell: bash
      commands:
      - ./build_all.sh
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishArtifactStep
    name: Publish build results
    sourcePath: bin
    artifacts: '**'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
- name: Github sync
  steps:
  - !PushRepository
    name: sync
    remoteUrl: https://github.com/JorriFransen/zodiac.git
    userName: jorri
    passwordSecret: ghsynctoken
    withLfs: false
    force: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  jobDependencies:
  - jobName: Test
    requireSuccessful: true
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
- name: Test
  jobExecutor: local-bare-metal-job-executor
  steps:
  - !CommandStep
    name: Run tests
    runInContainer: false
    interpreter: !ShellInterpreter
      shell: bash
      commands:
      - bin/zodiac
      - bin/zodiac_tests
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  jobDependencies:
  - jobName: Compile
    requireSuccessful: true
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
