
#run main();

main :: () {



    y := 1;

    for x := 0; x < 4; x += 1 {
        do_thing(x, y);
    }

    return 0;
}

do_thing :: (x: s64, y: s64) {

    switch (x) {
        case 1:
            if (y != 0) {
                println("x is one");
                if (y == x) {
                    println("y == x");
                } else {
                    println("y != x");
                }
            }

        case 2:
            println("x is two");
        //     if (y > x) {
        //         println("y > x");
        //     } else if (y == x) {
        //         println("y == x");
        //     } else {
        //         println("y <= x");
        //     }
        //
        // default:
        //     println("Default option for x");
    }

    // println();
}
