
#import "print.zc"

#run main();
main :: () {

    print_func("Hello!");
    println();
    print_func("Hello!", "World", 42);

    return 0;

}

print_func :: (fmt: String, args: ..) -> void {
    println("fmt: \"", fmt, "\"");
    print("args: ");

    for i := 0; i < args.length; i += 1 {
        if i > 0 print(", ");
        print_any(args[i]);
    }

    println();
}

// #foreign printf :: (cstr: *u8, args: ..) -> s32;

