
x :: y;
y :: z;
z :: 1;

//a :: b;
//b :: a;

//Vec2 :: struct {
//    x: r32;
//    y: r32;
//}
//
//AABB :: struct {
//    top_left, dim: Vec2;
//}
//
//Value :: union {
//    int_value: s32;
//    float_value: r32;
//}
//
//
//ptr : *s64 = null;
//var := 42;
//
//var2 : u16 = 8;
//var3 : s8;
//c_var :: 5;
//c_var2 : u32 : 2;
//
//main :: () -> s64 {
//
//    //foo : x; // Should generate "Not a type 'x'" error
//    str : String = "This is a string literal";
//    print(str);
//
//    return add_fn(40, 2);
//}
//
//add_fn :: (a: s64, b: s64) -> s64 {
//    //x := a;
//    result := a + b;
//    return result;
//}

