
//x :: y;
//y :: z;
//z :: 1;

xx :: yy;
yy :: zz;
zz :: xx;

//Vec2 :: struct {
//    x: r32;
//    y: r32;
//}
//
//AABB :: struct {
//    top_left, dim: Vec2;
//}
//
//Value :: union {
//    int_value: s32;
//    float_value: r32;
//}
//
//
//Ptr : *s64 = null;
//Var := 42;
//
//Var2 : u16 = 8;
//Var3 : s8;
//C_var :: 5;
//C_var2 : u32 : 2;
//
//Main :: () -> s64 {
//
//    //foo : x; // Should generate "Not a type 'x'" error
//    str : String = "This is a string literal";
//    print(str);
//
//    return add_fn(40, 2);
//}
//
//Add_fn :: (a: s64, b: s64) -> s64 {
//    result := a + b;
//    return result;
//}
//
